Repository Team-DeepGround/deep-ground-server-kakaoapi.ver, pull requests merged in 2025-08, with the labels that each got.

#19 [Feature] 스터디 그룹 집계 리스트 조회
  src/main/java/com/samsamhajo/deepground/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/samsamhajo/deepground/studyGroup/controller/CalculatedStudyGroupsInLocalController.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/CalculatedStudyGroupInLocalResponse.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/CalculatedStudyGroupsInLocalResponse.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/CalculatedStudyGroupsInLocalResultDto.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupAddressRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/CalculatedStudyGroupInLocalService.java
  src/test/java/com/samsamhajo/deepground/studyGroup/service/CalculatedStudyGroupInLocalServiceTest.java
Labels: feat

#21 [Feature] 지역별 스터디 그룹 목록 조회 API 구현
  src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupLocationController.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupsByLocationResponse.java
  src/main/java/com/samsamhajo/deepground/studyGroup/exception/StudyGroupErrorCode.java
  src/main/java/com/samsamhajo/deepground/studyGroup/exception/StudyGroupException.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupAddressRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupLocationService.java
  src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupLocationServiceTest.java
Labels: enhancement

#24 [Refactor] 스터디 일정 생성 관련 코드 리팩토링
  src/main/java/com/samsamhajo/deepground/calendar/dto/PlaceRequestDto.java
  src/main/java/com/samsamhajo/deepground/calendar/dto/SpecificAddressResponseDto.java
  src/main/java/com/samsamhajo/deepground/calendar/dto/StudyScheduleRequestDto.java
  src/main/java/com/samsamhajo/deepground/calendar/dto/StudyScheduleResponseDto.java
  src/main/java/com/samsamhajo/deepground/calendar/entity/StudySchedule.java
  src/main/java/com/samsamhajo/deepground/calendar/service/StudyScheduleService.java
  src/main/java/com/samsamhajo/deepground/communityPlace/entity/SpecificAddress.java
  src/main/java/com/samsamhajo/deepground/communityPlace/repository/SpecificAddressRepository.java
  src/main/java/com/samsamhajo/deepground/global/config/GeometryConfig.java
  src/test/java/com/samsamhajo/deepground/calendar/service/StudyScheduleServiceTest.java
Labels: feat

#26 [Fix] 컴파일 에러 수정
  src/main/java/com/samsamhajo/deepground/communityPlace/entity/CommunityPlaceReview.java
  src/main/java/com/samsamhajo/deepground/communityPlace/entity/SpecificAddress.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java
Labels: bug

#43 [Refactor] 리뷰 상세조회, 리스트조회 시 엔티티 컬럼 수정 & 로직 수정
  src/main/java/com/samsamhajo/deepground/admin/repository/AdminDashboardRepositoryImpl.java
  src/main/java/com/samsamhajo/deepground/calendar/dto/SpecificAddressResponseDto.java
  src/main/java/com/samsamhajo/deepground/calendar/entity/StudySchedule.java
  src/main/java/com/samsamhajo/deepground/communityPlace/controller/CommunityPlaceController.java
  src/main/java/com/samsamhajo/deepground/communityPlace/dto/request/CreateReviewDto.java
  src/main/java/com/samsamhajo/deepground/communityPlace/dto/request/ReviewDetailDto.java
  src/main/java/com/samsamhajo/deepground/communityPlace/dto/request/SearchReviewSummaryDto.java
  src/main/java/com/samsamhajo/deepground/communityPlace/dto/response/ReviewResponseDto.java
  src/main/java/com/samsamhajo/deepground/communityPlace/entity/CommunityPlaceReview.java
  src/main/java/com/samsamhajo/deepground/communityPlace/entity/SpecificAddress.java
  src/main/java/com/samsamhajo/deepground/communityPlace/repository/CommunityPlaceReviewRepository.java
  src/main/java/com/samsamhajo/deepground/communityPlace/repository/SpecificAddressRepository.java
  src/main/java/com/samsamhajo/deepground/communityPlace/service/CommunityPlaceService.java
  src/test/java/com/samsamhajo/deepground/admin/service/AdminServiceTest.java
Labels: enhancement

#46 [Fix] 지역 기준 스터디 그룹 목록 조회 오류 수정
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupLocationService.java
Labels: fix

#48 [Feature] 신고 관련 코드 추가
  build.gradle
  src/main/java/com/samsamhajo/deepground/admin/controller/AdminReportController.java
  src/main/java/com/samsamhajo/deepground/admin/dto/AdminDashboardStatsResponse.java
  src/main/java/com/samsamhajo/deepground/admin/exception/AdminErrorCode.java
  src/main/java/com/samsamhajo/deepground/admin/exception/AdminException.java
  src/main/java/com/samsamhajo/deepground/admin/repository/AdminDashboardRepository.java
  src/main/java/com/samsamhajo/deepground/admin/repository/AdminDashboardRepositoryImpl.java
  src/main/java/com/samsamhajo/deepground/admin/repository/AdminReportRepository.java
  src/main/java/com/samsamhajo/deepground/admin/service/AdminReportService.java
  src/main/java/com/samsamhajo/deepground/admin/service/AdminService.java
  src/main/java/com/samsamhajo/deepground/admin/success/AdminSuccessCode.java
  src/main/java/com/samsamhajo/deepground/auth/exception/AuthErrorCode.java
  src/main/java/com/samsamhajo/deepground/auth/service/AuthService.java
  src/main/java/com/samsamhajo/deepground/global/config/AIConfig.java
  src/main/java/com/samsamhajo/deepground/global/config/SecurityConfig.java
  src/main/java/com/samsamhajo/deepground/member/entity/Member.java
  src/main/java/com/samsamhajo/deepground/member/exception/MemberErrorCode.java
  src/main/java/com/samsamhajo/deepground/report/controller/ReportController.java
  src/main/java/com/samsamhajo/deepground/report/dto/AIReportResponse.java
  src/main/java/com/samsamhajo/deepground/report/dto/ReportRequest.java
  src/main/java/com/samsamhajo/deepground/report/dto/ReportResponse.java
  src/main/java/com/samsamhajo/deepground/report/entity/Report.java
  src/main/java/com/samsamhajo/deepground/report/enums/AIReviewResult.java
  src/main/java/com/samsamhajo/deepground/report/enums/ReportReason.java
  src/main/java/com/samsamhajo/deepground/report/enums/ReportTargetType.java
  src/main/java/com/samsamhajo/deepground/report/exception/ReportErrorCode.java
  src/main/java/com/samsamhajo/deepground/report/exception/ReportException.java
  src/main/java/com/samsamhajo/deepground/report/repository/ReportRepository.java
  src/main/java/com/samsamhajo/deepground/report/service/ReportPostAIClient.java
  src/main/java/com/samsamhajo/deepground/report/service/ReportService.java
  src/main/java/com/samsamhajo/deepground/report/success/ReportSuccessCode.java
  src/main/resources/application.yml
Labels: feat

#49 [Feat] 리뷰 조회 & 수정기능
  src/main/java/com/samsamhajo/deepground/communityPlace/controller/CommunityPlaceController.java
  src/main/java/com/samsamhajo/deepground/communityPlace/dto/request/ModifyReviewDto.java
  src/main/java/com/samsamhajo/deepground/communityPlace/dto/request/SummaryDto.java
  src/main/java/com/samsamhajo/deepground/communityPlace/dto/response/ModifyReviewResponseDto.java
  src/main/java/com/samsamhajo/deepground/communityPlace/entity/CommunityPlaceReview.java
  src/main/java/com/samsamhajo/deepground/communityPlace/exception/CommunityPlaceSuccessCode.java
  src/main/java/com/samsamhajo/deepground/communityPlace/repository/CommunityPlaceReviewRepository.java
  src/main/java/com/samsamhajo/deepground/communityPlace/service/CommunityPlaceService.java
Labels: enhancement

#53 [Fix] Jwt 및 관리자 관련 코드 수정
  src/main/java/com/samsamhajo/deepground/admin/controller/AdminReportController.java
  src/main/java/com/samsamhajo/deepground/admin/service/AdminReportService.java
  src/main/java/com/samsamhajo/deepground/admin/success/AdminSuccessCode.java
  src/main/java/com/samsamhajo/deepground/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/samsamhajo/deepground/auth/jwt/JwtProvider.java
  src/main/java/com/samsamhajo/deepground/auth/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/samsamhajo/deepground/auth/service/AuthService.java
  src/main/java/com/samsamhajo/deepground/report/dto/ReportDetailResponse.java
  src/main/java/com/samsamhajo/deepground/report/dto/ReportResponse.java
  src/main/java/com/samsamhajo/deepground/report/entity/Report.java
  src/test/java/com/samsamhajo/deepground/auth/jwt/JwtProviderTest.java
  src/test/java/com/samsamhajo/deepground/auth/service/RefreshAccessTokenTest.java
Labels: fix
